run cargo update to get rid of bad crossbeam-channel version 0.4.3
cargo-audit reported this:

error: Vulnerable crates found!

ID:       RUSTSEC-2020-0052
Crate:    crossbeam-channel
Version:  0.4.3
Date:     2020-06-26
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0052
Title:    Undefined Behavior in bounded channel
Solution:  upgrade to >= 0.4.4
Dependency tree:
crossbeam-channel 0.4.3
└── rayon-core 1.8.0
    └── rayon 1.4.0
        ├── remove_dir_all 0.6.0
        └── cargo-cache 0.5.1

warning: 1 warning found

Crate:    crossbeam-channel
Version:  0.4.3
Warning:  package has been yanked!

error: 1 vulnerability found!
warning: 1 warning found!